# Generated by Django 5.2.4 on 2025-10-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp activo'),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp activo'),
        ),
    ]
