# Generated by Django 5.2.4 on 2025-10-06 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_appointmentstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_group_booking',
            field=models.BooleanField(default=False, verbose_name='Permitir reservas múltiples'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_tickets_per_booking',
            field=models.PositiveIntegerField(default=1, verbose_name='Máx. boletos por reserva'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('allow_group_booking', False), ('max_tickets_per_booking__gte', 1), _connector='OR'), name='valid_max_tickets_group_booking'),
        ),
    ]
