# Generated by Django 5.2.4 on 2025-10-06 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_event_valid_max_tickets_group_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
